Ruby Project Two:  Enumerable Methods
RailonA/enumerable-methods pull request #1
Opened 2020-12-30 18:42 UTC by RailonA

This is the second project in the Ruby module. In this project, I rebuild my own iterator methods.

2020-12-30 22:31 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 

- Most of your methods are failing. Please read on for details on how to fix them:

Please use the following initial values to test your methods:
```
ARRAY_SIZE = 100
LOWEST_VALUE = 0
HIGHEST_VALUE = 9

array =  Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) } 
block =  proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } 
words =  %w[dog door rod blade] 
range =  Range.new(5, 50) 
hash =  { a: 1, b: 2, c: 3, d: 4, e: 5 } 
numbers =  [1, 2i, 3.14] 
array_clone =  array.clone 
```
- Your `my_each` displays the following errors. Please try testing the `expect`ed values to verify that they produce the desired output, as detailed in the error messages. If you have difficulty understanding the error messages, feel free to contact me on Slack. I'll be glad to help you out!

```
  1) enumerables #my_each returns an Enumerator if no block is given
     Failure/Error: expect(array.my_each).to be_an(Enumerator)
     
     LocalJumpError:
       no block given (yield)
     # ./enumerable.rb:6:in `block in my_each'
     # ./enumerable.rb:5:in `times'
     # ./enumerable.rb:5:in `my_each'
     # ./spec/enumerables_spec.rb:31:in `block (3 levels) in <top (required)>'

  2) enumerables #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self
     Failure/Error: expect(array.my_each(&block)).to eq(array.each(&block))
     
       expected: [3, 4, 5, 1, 8, 5, 3, 3, 1, 0, 1, 4, 1, 2, 6, 6, 7, 0, 3, 3, 6, 5, 1, 8, 3, 5, 8, 4, 2, 8, 2, 5, 7, 5..., 6, 5, 6, 6, 1, 6, 5, 3, 2, 4, 2, 3, 7, 1, 4, 7, 8, 2, 4, 5, 6, 5, 3, 5, 1, 4, 5, 5, 0, 2, 3, 4, 6]
            got: 100
     
       (compared using ==)
     # ./spec/enumerables_spec.rb:46:in `block (5 levels) in <top (required)>'

  3) enumerables #my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self
     Failure/Error: expect(range.my_each(&block)).to eq(range.each(&block))
     
     NameError:
       undefined local variable or method `length' for 5..50:Range
     # ./enumerable.rb:4:in `my_each'
     # ./spec/enumerables_spec.rb:56:in `block (5 levels) in <top (required)>'

  4) enumerables #my_each when a block is given when self is a range behaves like #each calls the given block once for each element in self
     Failure/Error: enum.my_each(&block)
     
     NameError:
       undefined local variable or method `length' for 5..50:Range
     Shared Example Group: "#each" called from ./spec/enumerables_spec.rb:51
     # ./enumerable.rb:4:in `my_each'
     # ./spec/enumerables_spec.rb:25:in `block (4 levels) in <top (required)>'

  5) enumerables #my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self
     Failure/Error: expect(my_each_output).to eq(each_output)
     
       expected: "[:a, 1][:b, 2][:c, 3][:d, 4][:e, 5]"
            got: ""
     
       (compared using ==)
     Shared Example Group: "#each" called from ./spec/enumerables_spec.rb:61
     # ./spec/enumerables_spec.rb:26:in `block (4 levels) in <top (required)>'
```
- Your `my_each_with_index` displays the following errors. Please try testing the `expect`ed values to verify that they produce the desired output, as detailed in the error messages. If you have difficulty understanding the error messages, feel free to contact me on Slack. I'll be glad to help you out!

```
  6) enumerables #my_each_with_index returns an enumerator if no block is given
     Failure/Error: expect(array.my_each_with_index).to be_an(Enumerator)
     
     NoMethodError:
       undefined method `my_each_with_index' for #<Array:0x00005592e1e28be0>
       Did you mean?  my_each_width_index
     # ./spec/enumerables_spec.rb:82:in `block (3 levels) in <top (required)>'

  7) enumerables #my_each_with_index does not mutate the original array
     Failure/Error: array.my_each_with_index { |num| num + 1 }
     
     NoMethodError:
       undefined method `my_each_with_index' for #<Array:0x00005592e1ea2648>
       Did you mean?  my_each_width_index
     # ./spec/enumerables_spec.rb:86:in `block (3 levels) in <top (required)>'

  8) enumerables #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self
     Failure/Error: expect(array.my_each_with_index(&block)).to eq(array.each_with_index(&block))
     
     NoMethodError:
       undefined method `my_each_with_index' for #<Array:0x00005592e1e753f0>
       Did you mean?  my_each_width_index
     # ./spec/enumerables_spec.rb:97:in `block (5 levels) in <top (required)>'

  9) enumerables #my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
     Failure/Error: enum.my_each_with_index(&block)
     
     NoMethodError:
       undefined method `my_each_with_index' for #<Array:0x00005592e1ec7bf0>
       Did you mean?  my_each_width_index
     Shared Example Group: "#each_with_index" called from ./spec/enumerables_spec.rb:92
     # ./spec/enumerables_spec.rb:76:in `block (4 levels) in <top (required)>'

  10) enumerables #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
      Failure/Error: expect(range.my_each_with_index(&block)).to eq(range.each_with_index(&block))
      
      NoMethodError:
        undefined method `my_each_with_index' for 5..50:Range
        Did you mean?  my_each_width_index
      # ./spec/enumerables_spec.rb:107:in `block (5 levels) in <top (required)>'

  11) enumerables #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
      Failure/Error: enum.my_each_with_index(&block)
      
      NoMethodError:
        undefined method `my_each_with_index' for 5..50:Range
        Did you mean?  my_each_width_index
      Shared Example Group: "#each_with_index" called from ./spec/enumerables_spec.rb:102
      # ./spec/enumerables_spec.rb:76:in `block (4 levels) in <top (required)>'

  12) enumerables #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
      Failure/Error: enum.my_each_with_index(&block)
      
      NoMethodError:
        undefined method `my_each_with_index' for {:a=>1, :b=>2, :c=>3, :d=>4, :e=>5}:Hash
        Did you mean?  my_each_width_index
      Shared Example Group: "#each_with_index" called from ./spec/enumerables_spec.rb:112
      # ./spec/enumerables_spec.rb:76:in `block (4 levels) in <top (required)>'
```
- Your `my_select` displays the following errors. Please try testing the `expect`ed values to verify that they produce the desired output, as detailed in the error messages. If you have difficulty understanding the error messages, feel free to contact me on Slack. I'll be glad to help you out!

```
  13) enumerables #my_select returns an array containing all elements of enum for which the given block returns a true value::range
      Failure/Error: expect(range.my_select(&block)).to eq(range.select(&block))
      
      NameError:
        undefined local variable or method `length' for 5..50:Range
      # ./enumerable.rb:4:in `my_each'
      # ./enumerable.rb:21:in `my_select'
      # ./spec/enumerables_spec.rb:125:in `block (3 levels) in <top (required)>'

  14) enumerables #my_select returns an enumerator if no block is given
      Failure/Error: expect(array.my_select).to be_an(Enumerator)
      
      LocalJumpError:
        no block given (yield)
      # ./enumerable.rb:22:in `block in my_select'
      # ./enumerable.rb:6:in `block in my_each'
      # ./enumerable.rb:5:in `times'
      # ./enumerable.rb:5:in `my_each [...]

2021-01-07 19:56 UTC, mimipeshy commented
## STATUS :CHANGES REQUIRED :red_circle: :recycle: 

Hello team :wave: :wave: good job on working on the feedback given above. Some methods are working, however, some are still failing, check out my comments below :arrow_down:

2021-01-07 20:02 UTC, mimipeshy commented on enumerable.rb
> +
enumerables #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self

2021-01-08 17:01 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
### Hey there :wave: 
#### You have made progress from the last review as you have gotten more test cases to pass. However, there are still cases that I will be listing out below. Please check them and make changes to get them to pass the test case.
- [ ] enumerables #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
     Failure/Error: expect(my_each_with_index_output).to eq(each_with_index_output)
- [ ] enumerables #my_all? when no block or argument is given returns true when none of the collection members are false or nil
     Failure/Error: expect(true_array.my_all?).to be true_array.all?
- [ ] enumerables #my_all? when no block or argument is given returns false when one of the collection members are false or nil
     Failure/Error: expect(false_array.my_all?).to be false_array.all?
- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
     Failure/Error: expect(array.my_all?(Integer)).to be array.all?(Integer)
- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
     Failure/Error: expect(numbers.my_all?(Numeric)).to be numbers.all?(Numeric)
- [ ] enumerables #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
     Failure/Error: expect(array.my_all?(Integer)).to be array.all?(Integer)
- [ ] enumerables #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
     Failure/Error: expect(words.my_all?(/d/)).to be words.all?(/d/)
- [ ] enumerables #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex
     Failure/Error: expect(words.my_all?(/o/)).to be words.all?(/o/)
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
     Failure/Error: expect(array.my_all?(3)).to be array.all?(3)
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
      Failure/Error: expect(array.my_all?(3)).to be array.all?(3)
- [ ] enumerables #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
      Failure/Error: expect(true_array.my_any?).to be true_array.any?
- [ ] enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true
      Failure/Error: expect(false_array.my_any?).to be false_array.any?
- [ ]  enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
      Failure/Error: expect(array.my_any?(Numeric)).to be array.any?(Numeric)
- [ ]  enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
      Failure/Error: expect(words.my_any?(Integer)).to be words.any?(Integer)
- [ ] enumerables #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
      Failure/Error: expect(words.my_any?(/d/)).to be words.any?(/d/)
- [ ] enumerables #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
      Failure/Error: expect(words.my_any?(/z/)).to be words.any?(/z/)
- [ ] enumerables #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
      Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
- [ ] enumerables #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
      Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
- [ ] enumerables #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
      Failure/Error: expect(array.my_map(my_proc) { |num| num < 10 }).to eq array.map(&my_proc)
- [ ]  enumerables #my_inject raises a "LocalJumpError" when no block or argument is given
      Failure/Error: expect { array.my_inject }.to raise_error(LocalJumpError)
        expected LocalJumpError but nothing was raised
- [ ] enumerables #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
      Failure/Error: expect(array.my_inject(:+)).to eq array.inject(:+)
- [ ] enumerables #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
      Failure/Error: expect(range.my_inject(:*)).to eq range.inject(:*)
- [ ] enumerables #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
      Failure/Error: expect(array.my_inject(20, :*)).to eq array.inject(20, :*)
- [ ] enumerables #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
      Failure/Error: expect(range.my_inject(2, :*)).to eq range.inject(2, :*)
#### Do reach out to me if you need help with anything and request another review once you are done making the changes.
slack(@ebeagusamuel)

2021-01-08 23:04 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done a great job on this project.
However, some changes are required before can be approved. Do not give up, you're almost there. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You still about 6 failed test cases. 5 of these failed test cases are from #my_none? while the sixth one is from #my_map. Let's check them out!
- **#my_none?**
  - should return false if the block ever returns true for all elements. A the moment, it returned true.
  - should return false if the block ever returns true for all elements::range (range of elements). At the moment, it returned true.
  - when no block or argument is given, it should return false only if one of the collection members is true. At the moment, it returned true.
  - when a Regex is passed as an argument, it should return false if any of the collection matches the Regex. At the moment, it returned true.
  - when a pattern other than Regex or a Class is given, it should return false only if one of the collections matches the pattern. At the moment, it returned true.
- **#my_map**
  - executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum. [i.e. expect(array.my_map(my_proc) { |num| num < 10 }).to eq array.map(&my_proc), but raised error: `ArgumentError: wrong number of arguments (given 1, expected 0)`].

**Note that I used the test cases used by the previous reviewers. Therefore, feel free to use the data as introduced by the first reviewer to test your data** 


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-01-09 11:48 UTC, mcrd25 requested changes
# Changes Required :mag: 

Hi @RailonA :wave: 

Good job so far, just a couple of minor changes required now! :muscle: 

#### Required Changes
- Remove all commented out code (See my comment on test.rb for explanation

POther than the commented out code issue, you have done a fantastic job! All tests pass now! :slightly_smiling_face: 

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2021-01-09 11:48 UTC, mcrd25 commented on test.rb
> +# p (1..10).each { |value| p value }
You ought not to have commented out code is committed. If you need to review a previous version of your code, use git history.

See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from our general requirements.

2021-01-09 11:48 UTC, mcrd25 commented on test.rb
> +# p (1..10).each { |value| p value }
You can consider also not committing/tracking test.rb altogether if it's for your personal use.

2021-01-09 12:05 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi @RailonA!

Thanks for the changes! You are now able to merge! :rocket: :tada: 

All good now!

2021-01-09 12:06 UTC, merged